DATA:
  data_root: /f2020/shengyifan/data/postdam1024  # data path
  train_list: ~/data/ADE20K/train.txt
  val_list: ~/data/ADE20K/val.txt
  classes: 6

TRAIN:
  arch: spnet
  spm_on: True
  layers: 101
  dataset: postdam
  backbone: resnet101
  sync_bn: True  # adopt sync_bn or not
  train_h: 780
  train_w: 780
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  aux_weight: 0.4
  train_gpu: [0, 1, 2, ]
  workers: 16  # data loader workers
  batch_size: 4  # batch size for training
  batch_size_val: 3  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.01
  epochs: 121
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed:
  print_freq: 20
  save_freq: 1
  save_path: savepath
  weight: /f2020/shengyifan/network/SPNet/pretrained/resnet101-2a57e44d.pth # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0
  use_apex: True
  opt_level: 'O0'
  keep_batchnorm_fp32:
  loss_scale:

TEST:
  test_list: ~/data/ADE20K/val.txt
  split: val  # split in [train, val and test]
  base_size: 512  # based size for scaling
  test_h: 480
  test_w: 480
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [0]
  model_path: modelpath  # evaluation model path
  save_folder: Res101S1024  # results save folder
  colors_path: /f2020/shengyifan/network/SPNet/dataset/postdam/postdam_colors.txt  # path of dataset colors
  names_path: /f2020/shengyifan/network/SPNet/dataset/postdam/postdam_names.txt  # path of dataset category names
